# Generated by Django 5.1.3 on 2024-11-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_Website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='first',
        ),
    ]
