# Generated by Django 5.1.3 on 2024-11-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_Website', '0002_rename_person_first'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='first',
            new_name='database1',
        ),
    ]
