# Generated by Django 5.1.3 on 2024-11-10 18:12

import E_Commerce_Website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_Website', '0003_rename_first_database1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=E_Commerce_Website.models.filename),
        ),
    ]
