# Generated by Django 5.1.3 on 2024-11-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_Website', '0004_alter_database1_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='database1',
            new_name='category',
        ),
    ]
